print('Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada')
a = int(input('Digite um número para ver sua tabuada: '))
print('_' * 12)
print('{} x {:2} = {}'.format(a, 1, (a*1)))
print('{} x {:2} = {}'.format(a, 2, (a*2)))
print('{} x {:2} = {}'.format(a, 3, (a*3)))
print('{} x {:2} = {}'.format(a, 4, (a*4)))
print('{} x {:2} = {}'.format(a, 5, (a*5)))
print('{} x {:2} = {}'.format(a, 6, (a*6)))
print('{} x {:2} = {}'.format(a, 7, (a*7)))
print('{} x {:2} = {}'.format(a, 8, (a*8)))
print('{} x {:2} = {}'.format(a, 9, (a*9)))
print('{} x {} = {}'.format(a, 10, (a*10)))
print('_' * 12)
